version: '3'
services:

  eureka-server:
    image: zahoriaut/eureka-server:0.1.5
    ports: 
      - "${ZAHORI_EUREKA_PORT}:8761"
    network_mode: bridge

  database:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "${ZAHORI_DB_PORT}:5432"
    network_mode: bridge
    environment:
     - POSTGRES_DB=${ZAHORI_DB_NAME}
     - POSTGRES_USER=${ZAHORI_DB_ADMIN_USER}
     - POSTGRES_PASSWORD=${ZAHORI_DB_ADMIN_PASS}
    volumes:
#     - ./database/postgres-data:/var/lib/postgresql/data
     - zahori-database:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:6.3.1
    command: -locations=filesystem:/flyway/sql -url=jdbc:postgresql://${ZAHORI_DB_HOST}:${ZAHORI_DB_PORT}/${ZAHORI_DB_NAME} -user=${ZAHORI_DB_ADMIN_USER} -password=${ZAHORI_DB_ADMIN_PASS} -placeholders.zahori_db_user=${ZAHORI_DB_USER} -placeholders.zahori_db_pass=${ZAHORI_DB_PASS} -baselineOnMigrate="false" -connectRetries=60 migrate
    network_mode: bridge
    links:
      - database
    volumes:
      - ./database/sql_versions:/flyway/sql
    depends_on:
      - database

  zahori-server:
    image: zahoriaut/zahori-server:0.1.7
    ports:
      - "${ZAHORI_SERVER_PORT}:${ZAHORI_SERVER_PORT}"
    network_mode: bridge
    links:
      - database
      - eureka-server
      - selenoid-ui
    environment:
     - ZAHORI_SERVER_PORT=${ZAHORI_SERVER_PORT}
     - ZAHORI_DB_HOST=${ZAHORI_DB_HOST}
     - ZAHORI_DB_PORT=${ZAHORI_DB_PORT}
     - ZAHORI_DB_NAME=${ZAHORI_DB_NAME}
     - ZAHORI_DB_SCHEMA=${ZAHORI_DB_SCHEMA}
     - ZAHORI_DB_USER=${ZAHORI_DB_USER}
     - ZAHORI_DB_PASS=${ZAHORI_DB_PASS}
     - ZAHORI_EUREKA_HOST=${ZAHORI_EUREKA_HOST}
     - ZAHORI_EUREKA_PORT=${ZAHORI_EUREKA_PORT}
     - ZAHORI_SELENOID_UI_INTERNAL_HOST=${ZAHORI_SELENOID_UI_INTERNAL_HOST}
     - ZAHORI_SELENOID_UI_INTERNAL_PORT=${ZAHORI_SELENOID_UI_INTERNAL_PORT}
     - ZAHORI_SELENOID_UI_EXTERNAL_HOST=${ZAHORI_SELENOID_UI_EXTERNAL_HOST}
     - ZAHORI_SELENOID_UI_EXTERNAL_PORT=${ZAHORI_SELENOID_UI_EXTERNAL_PORT}
    volumes:
     - ./evidences:/usr/app/evidences
    depends_on:
     - flyway
     - eureka-server
     - selenoid-ui

  chrome86:
    image: "selenoid/vnc_chrome:86.0"
  firefox81:
    image: "selenoid/vnc_firefox:81.0"
  safari13:
    image: "browsers/safari:13.0"
  edge88:
    image: "browsers/edge:88.0"
  opera71:
    image: "selenoid/vnc_opera:71.0"

  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    ports:
      - "${ZAHORI_SELENOID_PORT}:4444"
    volumes:
      - "./selenoid/config:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./selenoid/config/video:/opt/selenoid/video"
      - "./selenoid/config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=selenoid/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "5"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    ports:
      - "${ZAHORI_SELENOID_UI_INTERNAL_PORT}:8080"
    command: ["--selenoid-uri", "http://selenoid:${ZAHORI_SELENOID_PORT}", "--allowed-origin", "*"]
    depends_on:
     - selenoid
    network_mode: bridge
    links:
      - selenoid

volumes:
  zahori-database:
    external: true
